config/routes.rb
Rails.application.routes.draw do
  resources :data_analytics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "data_analytics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_analytic.rb
class DataAnalytic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/data_analytics_controller.rb
require 'csv'
require 'net/http/post/multipart'

class DataAnalyticsController < ApplicationController
  before_action :set_data_analytic, only: [:show, :edit, :update, :destroy]

  # GET /data_analytics
  # GET /data_analytics.json
  def index
    @data_analytics = DataAnalytic.all
  end

  # GET /data_analytics/1
  # GET /data_analytics/1.json
  def show
  end

  # GET /data_analytics/new
  def new
    @data_analytic = DataAnalytic.new
  end

  # GET /data_analytics/1/edit
  def edit
  end

  # POST /data_analytics
  # POST /data_analytics.json
  def create

    api_response = get_parsed_data(data_analytic_params[:file])

    api_response.each do |key,val|
      DataAnalytic.create(first_name: key,count: val)
    end

    respond_to do |format|
        format.html { redirect_to data_analytics_url, notice: 'Data analytic was successfully imported.' }
        format.json { render :show, status: :created }
    end
  end

  # PATCH/PUT /data_analytics/1
  # PATCH/PUT /data_analytics/1.json
  def update
    respond_to do |format|
      if @data_analytic.update(data_analytic_params)
        format.html { redirect_to @data_analytic, notice: 'Data analytic was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_analytic }
      else
        format.html { render :edit }
        format.json { render json: @data_analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_analytics/1
  # DELETE /data_analytics/1.json
  def destroy
    @data_analytic.destroy
    respond_to do |format|
      format.html { redirect_to data_analytics_url, notice: 'Data analytic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_parsed_data(file)

      url = URI.parse(API_URL)
      response = nil
      File.open(file.path) do |csv|
        req = Net::HTTP::Post::Multipart.new url.path,
                                             "csv" => UploadIO.new(csv, "text/csv", "test1.csv")
        response = Net::HTTP.start(url.host, url.port) do |http|
          http.request(req)
        end

      end
      JSON.parse(response.body)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_data_analytic
      @data_analytic = DataAnalytic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_analytic_params
      params.permit(:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_analytics_helper.rb
module DataAnalyticsHelper
end

app/views/data_analytics/_form.html.erb
<%= form_with(model: data_analytic, local: true, multipart: true) do |form| %>
  <% if data_analytic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_analytic.errors.count, "error") %> prohibited this data_analytic from being saved:</h2>

      <ul>
      <% data_analytic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag "Upload File to count first name" %>
    <%= file_field_tag :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_analytics/edit.html.erb
<h1>Editing Data Analytic</h1>

<%= render 'form', data_analytic: @data_analytic %>

<%= link_to 'Show', @data_analytic %> |
<%= link_to 'Back', data_analytics_path %>

app/views/data_analytics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data Analytics</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_analytics.each do |data_analytic| %>
      <tr>
        <td><%= data_analytic.first_name %></td>
        <td><%= data_analytic.count %></td>
        <td><%= link_to 'Show', data_analytic %></td>
        <td><%= link_to 'Edit', edit_data_analytic_path(data_analytic) %></td>
        <td><%= link_to 'Destroy', data_analytic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data Analytic', new_data_analytic_path %>

app/views/data_analytics/new.html.erb
<h1>New Data Analytic</h1>

<%= render 'form', data_analytic: @data_analytic %>

<%= link_to 'Back', data_analytics_path %>

app/views/data_analytics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @data_analytic.first_name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @data_analytic.count %>
</p>

<%= link_to 'Edit', edit_data_analytic_path(@data_analytic) %> |
<%= link_to 'Back', data_analytics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvParser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>